[connections.mysql]
dialect = "mysql"
host = "Sarfarajs-MacBook-Pro.local"
port = 8889
database = "restaurant_ratings"
username = "root"
password = "root"

[connections.aws_rds]
dialect = "mysql"
driver = "pymysql"
host = "adtprojectinstance1.c1w4kuymk7je.us-east-1.rds.amazonaws.com"
port = 3306
database = "restaurant_ratings"
username = "admin"
password = "adtproject123"